[package]
name = "milkshake-terminal"
version = "0.0.0"
edition = "2024"
rust-version = "1.93"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = { version = "0.22.1", default-features = false, features = ["std"] }
compact_str = { version = "0.9.0", default-features = false }
crossbeam-channel = { version = "0.5.15", default-features = false, features = [
    "std",
] }
bytemuck = { version = "1.25.0", default-features = false, features = [
    "derive",
] }
libc = { version = "0.2.183", default-features = false }
pollster = { version = "0.4.0", default-features = false }
vte = { version = "0.15.0", default-features = false }
wgpu = { version = "29.0.0", default-features = false, features = [
    "wgsl",
    "vulkan",
    "vulkan-portability",
    "metal",
] }
winit = { version = "0.31.0-beta.2", default-features = false }
ttf-parser = "0.25.1"
rayon = "1.11.0"

[target.'cfg(target_family = "unix")'.dependencies]
rustix-openpty = { version = "0.2.0", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", default-features = false, features = [
    "Win32_UI_WindowsAndMessaging",
] }

[dependencies.image]
version = "0.25.10"
default-features = false
features = ["jpeg", "png"]

[dependencies.rustix]
version = "1.1.4"
default-features = false
features = ["libc", "process", "std", "termios"]

[profile.dev]
opt-level = 2
strip = "symbols"

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["wayland"]
wayland = ["winit/wayland"]
x11 = ["winit/x11"]
android = ["winit/android-native-activity"]

[lints.clippy]
too_many_arguments = { level = "allow" }
